=== johnysmrz/clarus/core/ioc/beans.dtd
<!ELEMENT beans (bean+)>
<!ELEMENT bean (constructor-arg*)>
<!ATTLIST bean id ID #REQUIRED>
<!ATTLIST bean class CDATA #REQUIRED>
<!ELEMENT constructor-arg (ref?)>
<!ATTLIST constructor-arg index CDATA #IMPLIED>
<!ATTLIST constructor-arg value CDATA #REQUIRED>
<!ELEMENT ref ANY>
<!ATTLIST ref bean CDATA #REQUIRED>

=== johnysmrz/clarus/conf/ioc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans SYSTEM "beans.dtd">
<beans>
    <bean id="connection" class="\PDO">
        <constructor-arg value="pgsqlsss:dbname=test;host=127.0.0.1" />
        <constructor-arg value="postgres" />
        <constructor-arg value="pass" />
        <peel for="\clarus\clo\*" class="\PDO">
            <constructor-arg value="pgsql:dbname=test;host=127.0.0.1" />
            <constructor-arg value="postgres" />
            <constructor-arg value="pass" />
        </peel>
        <peel for="\clarus\clo\Clo" class="\PDO">
            <constructor-arg value="pgsql:dbname=app;host=127.0.0.1" />
            <constructor-arg value="postgres" />
            <constructor-arg value="pass" />
        </peel>
    </bean>
    <bean id="logger" class="\clarus\logger">

    </bean>
</beans>
